Badminton-Apps/badman

- README.md
> docs: npm install instructions in README

- README.md
> docs: Added yarn instead of yat

- code/frontend/packages/ranking-client/src/app/_shared/graphql/rankingSystem/queries/GetPrimarySystemsQuery.graphql
- code/frontend/packages/ranking-client/src/app/_shared/models/ranking-system.model.ts
- code/frontend/packages/ranking-client/src/app/_shared/services/system/system.service.ts
- code/frontend/packages/ranking-client/src/app/player/page/top-players/top-players.component.ts
> fix: Show topplayers from last run

- .github/workflows/publish.yaml
- .gitignore
- README.md
- code/backend/packages/_shared/package.json
- code/backend/packages/_shared/utils/generate-erd.ts
- code/backend/packages/server/src/controllers/ranking.controller.ts
- code/backend/packages/server/src/controllers/request-link.controller.ts
- code/backend/packages/server/src/server.ts
- code/backend/yarn.lock
> feat: add erd generator on publish

- .github/workflows/pr.yaml
- code/backend/packages/_shared/.babelrc
- code/backend/packages/_shared/__tests__/config.spec.tsx
- code/backend/packages/_shared/database/database.config.js
- code/backend/packages/_shared/jest.config.js
- code/backend/packages/_shared/package.json
- code/backend/packages/_shared/tsconfig.json
- code/backend/packages/_shared/utils/__tests__/logger.tsx
- code/backend/packages/import/package.json
- code/backend/packages/server/jest.config.js
- code/backend/packages/server/package.json
- code/backend/packages/simulate/jest.config.js
- code/backend/packages/simulate/package.json
> More things

- code/frontend/packages/ranking-client/src/app/_shared/graphql/players/queries/GetUserGamesQuery.graphql
- code/frontend/packages/ranking-client/src/app/_shared/graphql/rankingSystem/queries/GetPrimarySystemsQuery.graphql
- code/frontend/packages/ranking-client/src/app/_shared/models/game.model.ts
- code/frontend/packages/ranking-client/src/app/_shared/services/player/player.service.ts
- code/frontend/packages/ranking-client/src/app/player/page/player/components/games/games.component.ts
- code/frontend/packages/ranking-client/src/app/player/page/player/components/player-info/player-info.component.scss
- code/frontend/packages/ranking-client/src/app/player/page/player/components/player-info/player-info.component.ts
> fix: moved the system info to single query

- .github/workflows/publish.yaml
- code/frontend/package.json
- code/frontend/packages/client/angular.json
- code/frontend/packages/client/karma.conf.js
- code/frontend/packages/client/package.json
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/import/components/add-event.dialog/index.ts
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/import/components/index.ts
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/import/components/upload-field/index.ts
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/import/directives/index.ts
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/import/index.ts
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/index.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/components/edit-ranking/index.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/components/index.ts
- code/frontend/packages/client/src/app/club/dialogs/index.ts
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/components/location-fields/index.ts
- code/frontend/packages/client/src/app/competition/components/index.ts
- code/frontend/packages/client/src/app/competition/components/select-event/index.ts
- code/frontend/packages/client/tsconfig.app.json
- code/frontend/packages/client/tsconfig.json
- code/frontend/packages/client/tsconfig.spec.json
- code/frontend/yarn.lock
> fix: testing FE

- .github/workflows/pr.yaml
> ci: add caching to pr

- .github/workflows/publish.yaml
> ci: add codecov on publish

- code/backend/packages/import/charts/import/templates/deployment.yaml
- code/backend/packages/server/charts/server/templates/deployment.yaml
- code/backend/packages/simulate/charts/simulate/templates/deployment.yaml
- code/backend/packages/supervisor/charts/supervisor/templates/deployment.yaml
- code/frontend/packages/client/charts/client/templates/deployment.yaml
> feat: liveness/readiness probes

- code/backend/packages/_shared/models/sequelize/club.model.ts
> fix: admin role creation

- code/backend/packages/_shared/models/sequelize/club.model.ts
> fixup! fix: admin role creation

- code/frontend/packages/client/src/app/admin/modules/club-management/pages/edit-club/components/club-edit-role/club-edit-role.component.html
- code/frontend/packages/client/src/app/admin/modules/event-management/pages/import/import.component.html
- code/frontend/packages/client/src/app/club/dialogs/team-dialog/components/team-players/team-players.component.html
> fix: icon was accedently translated

- code/frontend/packages/client/src/app/competition/modules/team-enrollment/pages/components/assign-team/assign-team.component.html
- code/frontend/packages/client/src/app/competition/modules/team-enrollment/pages/components/assign-team/assign-team.component.ts
> fix(client): wait for translations

- code/backend/packages/import/src/import/processors/competition.ts
- code/backend/packages/import/src/import/processors/competition_cp.ts
- code/backend/packages/import/src/import/processors/competition_xml.ts
- code/backend/packages/import/src/import/processors/tournament.ts
> feat(import): Remember subEvent config from prev import

- code/backend/packages/_shared/models/sequelize/event/tournament/sub-event-tournament.model.ts
- code/backend/packages/import/src/import/processors/competition.ts
- code/backend/packages/import/src/import/processors/competition_cp.ts
- code/backend/packages/import/src/import/processors/competition_xml.ts
- code/backend/packages/import/src/import/processors/tournament.ts
> feat(import): copy ranking groups when an existing event is overwritten

- code/backend/packages/_shared/services/authentication/authentication.service.ts
- code/frontend/packages/client/package.json
> fix: Not being logged in causes most API calls to fail

- code/frontend/packages/client/src/app/admin/modules/club-management/pages/edit-club/components/club-edit-location/club-edit-location.component.html
- code/frontend/packages/client/src/app/admin/modules/club-management/pages/edit-club/edit-club.component.html
- code/frontend/packages/client/src/app/admin/modules/club-management/pages/edit-club/edit-club.component.ts
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/components/location-fields/location-fields.component.html
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/location-dialog.component.scss
real issue was the api-key didn't allow new url :P
fixes: #84
> fix: #84 - Search for location crashes

- code/frontend/packages/client/src/app/club/dialogs/team-dialog/team-dialog.component.scss
> fix: #86 - [BUG] Team edit window incompatible with browser

- code/backend/packages/import/src/import/processors/competition_xml.ts
> fix: #90 - [BUG] Importing competition crashes

- code/backend/packages/simulate/src/models/rankingCalc.ts
- code/backend/packages/simulate/src/models/rankingTypes/bvl.ts
- code/backend/packages/simulate/src/models/rankingTypes/lfbb.ts
> feat: split simulation in smaller blocks

- code/backend/yarn.lock
- code/frontend/packages/client/src/app/_shared/models/player.model.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/components/edit-player-fields/edit-player-fields.component.html
- code/frontend/packages/client/src/app/admin/modules/player-management/components/edit-player-fields/edit-player-fields.component.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/components/edit-player-fields/index.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/components/index.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/pages/edit-player/edit-player.component.html
- code/frontend/packages/client/src/app/admin/modules/player-management/pages/edit-player/edit-player.component.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/player-management.module.ts
- code/frontend/packages/client/src/assets/i18n/en.json
- code/frontend/packages/client/src/assets/i18n/fr_BE.json
- code/frontend/packages/client/src/assets/i18n/nl_BE.json
> feat: Add edit player

- code/frontend/packages/client/src/app/_shared/models/player.model.ts
- code/frontend/packages/client/src/app/admin/modules/player-management/components/edit-player-fields/edit-player-fields.component.html
- code/frontend/packages/client/src/app/admin/modules/player-management/components/edit-player-fields/edit-player-fields.component.ts
> fix: parsing, required, only update new

- code/backend/packages/import/package.json
- code/backend/packages/import/src/controllers/import.controller.ts
- code/backend/packages/simulate/src/models/rankingTypes/bvl.ts
- code/backend/packages/simulate/src/models/rankingTypes/lfbb.ts
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/components/new-player/new-player.component.html
- code/frontend/packages/client/src/app/_shared/graphql/clubs/queries/GetClubsQuery.graphql
- code/frontend/packages/client/src/app/admin/modules/club-management/components/club-fields/club-fields.component.html
- code/frontend/packages/client/src/app/admin/modules/club-management/components/club-fields/club-fields.component.ts
- code/frontend/packages/client/src/app/club/pages/overview-clubs/overview-clubs.component.html
- code/frontend/packages/client/src/app/club/pages/overview-clubs/overview-clubs.component.ts
- code/frontend/packages/client/src/app/competition/modules/team-enrollment/pages/components/assign-team/assign-team.component.ts
- code/frontend/packages/client/src/assets/i18n/en.json
- code/frontend/packages/client/src/assets/i18n/fr_BE.json
- code/frontend/packages/client/src/assets/i18n/nl_BE.json
> Fix/#102 feature club number (in list and edit)

- code/backend/packages/server/src/controllers/user.controller.ts
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/ranking-shell.component.html
> fix: show "my club(s)" in sidebar

- code/frontend/packages/client/src/app/competition/modules/team-enrollment/pages/graphql/GetClub.graphql
> fix: Notification/check max level gone (and should not be for 1st team)

- code/backend/packages/_shared/app.ts
- code/backend/packages/_shared/database/migrations/20210425090718-delete club.js
- code/backend/packages/server/src/graphql/mutations/club.mutations.ts
- code/backend/packages/server/src/graphql/schema.ts
- code/frontend/packages/client/src/app/_shared/graphql/clubs/mutations/removeClub.graphql
- code/frontend/packages/client/src/app/_shared/services/club/club.service.ts
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/components/location-fields/location-fields.component.ts
- code/frontend/packages/client/src/app/club/pages/detail-club/detail-club.component.html
- code/frontend/packages/client/src/app/club/pages/detail-club/detail-club.component.ts
- code/frontend/schema.graphql
> fix: Change locations without searching not saving

- code/frontend/packages/client/src/app/admin/modules/club-management/components/club-fields/club-fields.component.html
> fix: Cannot remove club

- code/frontend/packages/client/src/app/_shared/graphql/clubs/queries/GetClubQuery.graphql
- code/frontend/packages/client/src/app/_shared/graphql/locations/queries/GetLocationQuery.graphql
- code/frontend/packages/client/src/app/_shared/shared.module.ts
- code/frontend/packages/client/src/app/admin/modules/club-management/pages/edit-club/components/club-edit-location/club-edit-location.component.html
- code/frontend/packages/client/src/app/admin/modules/club-management/pages/edit-club/components/club-edit-location/club-edit-location.component.scss
- code/frontend/packages/client/src/app/app.module.ts
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/components/location-fields/location-fields.component.html
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/components/location-fields/location-fields.component.scss
- code/frontend/packages/client/src/app/club/dialogs/location-dialog/components/location-fields/location-fields.component.ts
- code/frontend/packages/client/src/app/competition/components/competition-components.module.ts
- code/frontend/packages/client/src/app/competition/modules/match-form/match-form.module.ts
- code/frontend/packages/client/src/app/info/info.module.ts
- code/frontend/packages/client/src/app/tournament/tournament.module.ts
> feat:  Improved visualization location

- code/frontend/packages/client/src/app/club/dialogs/team-dialog/components/team-players/team-players.component.html
- code/frontend/packages/client/src/app/club/pages/detail-club/components/team-overview/team-overview.component.html
- code/frontend/packages/client/src/assets/i18n/en.json
- code/frontend/packages/client/src/assets/i18n/fr_BE.json
- code/frontend/packages/client/src/assets/i18n/nl_BE.json
> fix: Translation

- code/backend/packages/server/src/controllers/user.controller.ts
- code/backend/packages/server/src/graphql/types/club.type.ts
- code/backend/packages/server/src/graphql/types/player.type.ts
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/components/player-search/player-search.component.ts
> feat: only show active club

- code/backend/packages/_shared/database/migrations/20210730113056-Captain information.js
- code/backend/packages/_shared/models/sequelize/team.model.ts
- code/frontend/packages/client/src/app/_shared/graphql/teams/queries/GetTeamQuery.graphql
- code/frontend/packages/client/src/app/_shared/models/team.model.ts
- code/frontend/packages/client/src/app/club/dialogs/team-dialog/components/team-fields/team-fields.component.html
- code/frontend/packages/client/src/app/club/dialogs/team-dialog/components/team-fields/team-fields.component.ts
- code/frontend/packages/client/src/app/club/dialogs/team-dialog/team-dialog.component.html
> feat: Store captain information

- code/frontend/packages/client/src/app/_shared/services/player/player.service.ts
> Fix/player ranking not\wrong showing

- code/frontend/packages/client/src/app/player/page/player/components/games/games.component.ts
> fixup! 5034588544c682ad3b13f3ded887202cfe7158a3

- code/backend/packages/_shared/database/migrations/20211214110221-Encounter result.js
- code/backend/packages/_shared/models/rankingTypes/rankingCalc.ts
- code/backend/packages/_shared/models/sequelize/event/competition/encounter-competition.model.ts
- code/backend/packages/_shared/models/sequelize/event/game.model.ts
- code/backend/packages/jobs/src/models/jobs/get-scores-visual/competition-sync/competition-sync.ts
- code/backend/packages/jobs/src/models/jobs/get-scores-visual/tournament-sync/tournament-sync.ts
- code/backend/packages/jobs/src/models/jobs/run-scores-visual.ts
- code/frontend/packages/client/src/app/_shared/graphql/players/queries/GetUserGamesQuery.graphql
- code/frontend/packages/client/src/app/_shared/models/events/competition/encounter.model.ts
- code/frontend/packages/client/src/app/player/page/player/components/games/components/games-result/group-competition/group-competition.component.html
- code/frontend/packages/client/src/app/player/page/player/components/games/components/games-result/group-competition/group-competition.component.scss
- code/frontend/schema.graphql
> feat: showing competition score

- code/backend/packages/_shared/index.ts
- code/backend/packages/_shared/package.json
- code/backend/packages/_shared/types/index.ts
- code/backend/packages/server/package.json
- code/backend/scripts/basic/src/generate-slugs.ts
> fix: package reference should be for shared

- code/backend/packages/_shared/database/migrations/20220115114512-Store gender in ranking places.js
- code/backend/packages/_shared/models/sequelize/ranking/last-place.model.ts
- code/backend/packages/_shared/models/sequelize/ranking/place.model.ts
- code/backend/packages/_shared/models/sequelize/ranking/system.model.ts
- code/backend/packages/server/src/controllers/ranking.controller.ts
- code/backend/packages/server/src/graphql/types/attributes.type.ts
- code/backend/packages/server/src/graphql/types/player.type.ts
- code/backend/packages/server/src/graphql/types/rankingPlace.type.ts
- code/backend/packages/server/src/graphql/types/rankingSystem.type.ts
- code/frontend/packages/client/src/app/club/pages/overview-clubs/overview-clubs.component.html
- code/frontend/packages/client/src/app/club/pages/overview-clubs/overview-clubs.component.ts
- code/frontend/packages/client/src/app/player/page/top-players/top-players.component.html
- code/frontend/packages/client/src/app/player/page/top-players/top-players.component.scss
- code/frontend/packages/client/src/app/player/page/top-players/top-players.component.ts
- code/frontend/packages/client/src/app/player/player.module.ts
- code/frontend/packages/client/src/assets/i18n/nl_BE.json
> feat: Ranking players via graphql

- code/backend/packages/search/src/__tests__/server.spec.tsx
- code/backend/packages/search/src/controllers/search.controller.ts
- code/backend/packages/server/src/graphql/types/rankingSystem.type.ts
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/components/header-search/header-search.component.html
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/components/header-search/header-search.component.ts
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/ranking-shell.component.html
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/ranking-shell.component.ts
- code/frontend/packages/client/src/app/_shared/services/player/player.service.ts
- code/frontend/packages/client/src/assets/i18n/nl_BE.json
> fix: Enhance search for allowing events and clubs

- code/backend/packages/server/src/graphql/mutations/player.mutations.ts
- code/backend/packages/server/src/server.ts
- code/frontend/packages/client/src/app/_shared/models/player.model.ts
- code/frontend/packages/client/src/app/competition/modules/team-assembly/pages/team-assembly/components/assembly/assembly.component.ts
- code/frontend/packages/client/src/app/player/page/edit-player/tabs/edit-ranking/edit-ranking.component.ts
> fix: check for competition player not working

- code/frontend/packages/client/src/app/_shared/components/ranking-shell/ranking-shell.component.scss
- code/frontend/packages/client/src/app/_shared/shared.module.ts
- code/frontend/packages/client/src/app/app-routing.module.ts
- code/frontend/packages/client/src/app/competition/modules/team-assembly/pages/team-assembly/team-assembly.component.ts
- code/frontend/packages/client/src/app/training/index.ts
- code/frontend/packages/client/src/app/training/pages/curriculum/curriculum.component.html
- code/frontend/packages/client/src/app/training/pages/curriculum/curriculum.component.scss
- code/frontend/packages/client/src/app/training/pages/curriculum/curriculum.component.ts
- code/frontend/packages/client/src/app/training/pages/curriculum/index.ts
- code/frontend/packages/client/src/app/training/pages/index.ts
- code/frontend/packages/client/src/app/training/training-routing.module.ts
- code/frontend/packages/client/src/app/training/training.module.ts
> feat: POC trainer

- code/frontend/packages/client/src/app/_shared/components/ranking-shell/components/header-search/header-search.component.scss
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/ranking-shell.component.html
- code/frontend/packages/client/src/app/_shared/components/ranking-shell/ranking-shell.component.scss
- code/frontend/packages/client/src/app/competition/modules/team-assembly/pages/team-assembly/team-assembly.component.scss
- code/frontend/packages/client/src/styles.scss
> fix(client): Small screens didn't have login button visible

- code/backend/scripts/basic/package.json
- code/backend/scripts/basic/src/fix-fix-meta.ts
> fix: Meta was stored incorrectly, this script fixes it

- code/libs/frontend/club/src/pages/detail-club/detail-club.component.ts
> fix(frontend-club): mixed teams had no index

- code/apps/api/src/app/services/pdf.service.ts
- code/libs/backend/database/src/models/event/competition/event-competition.model.ts
> fix(api): fetching only the needed data

- code/package.json
- code/yarn.lock
> chore(deps): removing depricated pacakge

- code/libs/backend/graphql/src/resolvers/player/player.resolver.ts
- code/libs/frontend/club/src/pages/detail-club/detail-club.component.html
- code/libs/frontend/club/src/pages/detail-club/detail-club.component.ts
- code/libs/frontend/components/player-search/src/components/player-search/player-search.component.ts
- code/libs/frontend/shared/src/graphql/players/mutations/AddPlayerMutation.graphql
- code/schema/schema.gql
> fix(frontend-club): adding player to a club

- libs/backend/graphql/src/resolvers/event/competition/encounter-change.resolver.ts
- the code was using bad methods to fetch certain data, which would cause the EventCompetition data to sometimes not load, or be incomplete.  This fix ensures that this data is consistent
> added: a fix for random request failure

- apps/worker/sync/src/app/processors/enter-scores/pupeteer/clearFields.ts
- apps/worker/sync/src/app/processors/sync-events/competition-sync/processors/game.ts
- added a chdeck to see if the encounter date is not undefined, to see if that fixes the 'empty' game reocrds issue
> some small changes

- apps/api/project.json
- apps/worker/sync/src/app/processors/check-encounters/check-encounters.processor.ts
- apps/worker/sync/src/app/processors/check-ranking/get-ranking.processor.ts
- apps/worker/sync/src/app/processors/enter-scores/enter-scores.processor.ts
- libs/backend/graphql/src/resolvers/event/competition/encounter.resolver.ts
- added dependsOn: [^build] to project.json file for api
- added some cleanup functions for puppeteer processors
- added some more standard return structures for resolvers on the encounter-competition resolver
> added: a fix for the ranking upload

- libs/backend/database/src/models/ranking/ranking-place.model.ts
- libs/backend/ranking/src/services/update-ranking/update-ranking.service.ts
> fix: improve ranking updates by using findOrCreate and updating existing instances
